const translations = {
    zh: {
        score: "分数",
        lives: "生命",
        paused: "已暂停",
        gameOver: "游戏结束",
        finalScore: "最终得分",
        highScore: "最高分",
        playAgain: "再玩一次",
        mainMenu: "主菜单",
        startGame: "开始游戏",
        instructions: "游戏说明",
        settings: "设置",
        back: "返回",
        difficulty: "难度",
        easy: "简单",
        normal: "普通",
        hard: "困难",
        sound: "声音",
        on: "开",
        off: "关",
        language: "语言"
    },
    en: {
        score: "Score",
        lives: "Lives",
        paused: "Paused",
        gameOver: "Game Over",
        finalScore: "Final Score",
        highScore: "High Score",
        playAgain: "Play Again",
        mainMenu: "Main Menu",
        startGame: "Start Game",
        instructions: "Instructions",
        settings: "Settings",
        back: "Back",
        difficulty: "Difficulty",
        easy: "Easy",
        normal: "Normal",
        hard: "Hard",
        sound: "Sound",
        on: "On",
        off: "Off",
        language: "Language"
    }
};
