export const LEVELS = [
    {
        id: 1,
        code: "L01",
        name: "晨光入口",
        rows: 9,
        cols: 9,
        generator: "dfs",
        seed: 11001,
        visionRadius: 4,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["tutorial", "short-path"],
        targetTimeSec: 40,
        targetMoves: 24
    },
    {
        id: 2,
        code: "L02",
        name: "双岔回廊",
        rows: 10,
        cols: 10,
        generator: "dfs",
        seed: 11002,
        visionRadius: 4,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["forks", "backtrack"],
        targetTimeSec: 50,
        targetMoves: 30
    },
    {
        id: 3,
        code: "L03",
        name: "盲角小径",
        rows: 11,
        cols: 11,
        generator: "dfs",
        seed: 11003,
        visionRadius: 3,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["dead-ends", "memory"],
        targetTimeSec: 60,
        targetMoves: 38
    },
    {
        id: 4,
        code: "L04",
        name: "低照地带",
        rows: 11,
        cols: 13,
        generator: "dfs",
        seed: 11004,
        visionRadius: 3,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["low-vision"],
        targetTimeSec: 70,
        targetMoves: 44
    },
    {
        id: 5,
        code: "L05",
        name: "铜钥之门",
        rows: 12,
        cols: 12,
        generator: "dfs",
        seed: 11005,
        visionRadius: 3,
        objective: "collect-key-and-exit",
        timerSec: null,
        challengeTags: ["key-door"],
        targetTimeSec: 75,
        targetMoves: 46
    },
    {
        id: 6,
        code: "L06",
        name: "信标试炼",
        rows: 12,
        cols: 13,
        generator: "dfs",
        seed: 11006,
        visionRadius: 3,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["beacon", "buff-validation"],
        targetTimeSec: 80,
        targetMoves: 50
    },
    {
        id: 7,
        code: "L07",
        name: "泥沼边界",
        rows: 13,
        cols: 13,
        generator: "dfs",
        seed: 11007,
        visionRadius: 3,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["slow-tiles"],
        targetTimeSec: 90,
        targetMoves: 56
    },
    {
        id: 8,
        code: "L08",
        name: "镜面跃迁",
        rows: 13,
        cols: 14,
        generator: "dfs",
        seed: 11008,
        visionRadius: 3,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["teleport-pair"],
        targetTimeSec: 95,
        targetMoves: 58
    },
    {
        id: 9,
        code: "L09",
        name: "单行岔口",
        rows: 14,
        cols: 14,
        generator: "dfs",
        seed: 11009,
        visionRadius: 3,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["one-way-gate"],
        targetTimeSec: 100,
        targetMoves: 62
    },
    {
        id: 10,
        code: "L10",
        name: "倒计时走廊",
        rows: 14,
        cols: 15,
        generator: "dfs",
        seed: 11010,
        visionRadius: 3,
        objective: "reach-exit",
        timerSec: 90,
        challengeTags: ["timer"],
        targetTimeSec: 85,
        targetMoves: 60
    },
    {
        id: 11,
        code: "L11",
        name: "暗雾陷阱",
        rows: 15,
        cols: 15,
        generator: "dfs",
        seed: 11011,
        visionRadius: 2,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["vision-debuff", "trap-tiles"],
        targetTimeSec: 110,
        targetMoves: 70
    },
    {
        id: 12,
        code: "L12",
        name: "双钥封锁",
        rows: 15,
        cols: 16,
        generator: "dfs",
        seed: 11012,
        visionRadius: 3,
        objective: "collect-two-keys-and-exit",
        timerSec: null,
        challengeTags: ["dual-keys", "route-planning"],
        targetTimeSec: 120,
        targetMoves: 76
    },
    {
        id: 13,
        code: "L13",
        name: "隐线捷径",
        rows: 16,
        cols: 16,
        generator: "dfs",
        seed: 11013,
        visionRadius: 2,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["hidden-shortcut", "exploration-reward"],
        targetTimeSec: 125,
        targetMoves: 78
    },
    {
        id: 14,
        code: "L14",
        name: "压板回路",
        rows: 16,
        cols: 17,
        generator: "dfs",
        seed: 11014,
        visionRadius: 3,
        objective: "activate-plate-and-exit",
        timerSec: null,
        challengeTags: ["pressure-plate", "sequence"],
        targetTimeSec: 130,
        targetMoves: 82
    },
    {
        id: 15,
        code: "L15",
        name: "余辉灯塔",
        rows: 17,
        cols: 17,
        generator: "prim",
        seed: 11015,
        visionRadius: 2,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["multi-beacon", "buff-management"],
        targetTimeSec: 135,
        targetMoves: 84
    },
    {
        id: 16,
        code: "L16",
        name: "跃迁串链",
        rows: 17,
        cols: 18,
        generator: "prim",
        seed: 11016,
        visionRadius: 2,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["teleport-chain", "orientation"],
        targetTimeSec: 145,
        targetMoves: 90
    },
    {
        id: 17,
        code: "L17",
        name: "黑核迷城",
        rows: 18,
        cols: 18,
        generator: "prim",
        seed: 11017,
        visionRadius: 2,
        objective: "reach-exit",
        timerSec: null,
        challengeTags: ["low-vision", "long-route"],
        targetTimeSec: 155,
        targetMoves: 96
    },
    {
        id: 18,
        code: "L18",
        name: "分流枢纽",
        rows: 18,
        cols: 19,
        generator: "prim",
        seed: 11018,
        visionRadius: 2,
        objective: "collect-key-and-exit",
        timerSec: 150,
        challengeTags: ["multi-route", "timer", "decision-pressure"],
        targetTimeSec: 145,
        targetMoves: 92
    },
    {
        id: 19,
        code: "L19",
        name: "终幕前厅",
        rows: 19,
        cols: 19,
        generator: "prim",
        seed: 11019,
        visionRadius: 2,
        objective: "collect-two-keys-and-exit",
        timerSec: 165,
        challengeTags: ["compound-mechanics", "dual-keys", "teleport-pair", "timer"],
        targetTimeSec: 160,
        targetMoves: 104
    },
    {
        id: 20,
        code: "L20",
        name: "深渊主迷宫",
        rows: 20,
        cols: 20,
        generator: "prim",
        seed: 11020,
        visionRadius: 2,
        objective: "final-relay",
        timerSec: 180,
        challengeTags: ["final-trial", "beacon", "dual-keys", "pressure-plate", "teleport-chain", "timer"],
        targetTimeSec: 175,
        targetMoves: 118
    }
];
